import React from 'react'
import './Policy.css';
const Policy = () => {
  return (
    <div className='policy_details'>
        <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eos, iusto neque dolore officiis mollitia unde, quod sed fugiat sapiente doloribus a repellat. Ipsum doloremque, reprehenderit quisquam fugit voluptatum quae, deserunt cumque asperiores enim nemo ullam, doloribus laudantium. Aperiam ut asperiores eum ullam distinctio saepe molestiae perspiciatis, eveniet odio deleniti corporis, enim, ipsam nostrum impedit provident voluptate fugiat? Minima eligendi recusandae unde tempore magnam, aliquid quas officia itaque est cupiditate quos harum dignissimos soluta. Fuga inventore nobis ea incidunt qui ut ullam delectus et, placeat blanditiis, fugiat accusantium. Impedit nisi delectus, architecto omnis velit natus, praesentium quidem quaerat soluta explicabo atque.</p>
        <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eos, iusto neque dolore officiis mollitia unde, quod sed fugiat sapiente doloribus a repellat. Ipsum doloremque, reprehenderit quisquam fugit voluptatum quae, deserunt cumque asperiores enim nemo ullam, doloribus laudantium. Aperiam ut asperiores eum ullam distinctio saepe molestiae perspiciatis, eveniet odio deleniti corporis, enim, ipsam nostrum impedit provident voluptate fugiat? Minima eligendi recusandae unde tempore magnam, aliquid quas officia itaque est cupiditate quos harum dignissimos soluta. Fuga inventore nobis ea incidunt qui ut ullam delectus et, placeat blanditiis, fugiat accusantium. Impedit nisi delectus, architecto omnis velit natus, praesentium quidem quaerat soluta explicabo atque.</p>
        <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eos, iusto neque dolore officiis mollitia unde, quod sed fugiat sapiente doloribus a repellat. Ipsum doloremque, reprehenderit quisquam fugit voluptatum quae, deserunt cumque asperiores enim nemo ullam, doloribus laudantium. Aperiam ut asperiores eum ullam distinctio saepe molestiae perspiciatis, eveniet odio deleniti corporis, enim, ipsam nostrum impedit provident voluptate fugiat? Minima eligendi recusandae unde tempore magnam, aliquid quas officia itaque est cupiditate quos harum dignissimos soluta. Fuga inventore nobis ea incidunt qui ut ullam delectus et, placeat blanditiis, fugiat accusantium. Impedit nisi delectus, architecto omnis velit natus, praesentium quidem quaerat soluta explicabo atque.</p>
        <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eos, iusto neque dolore officiis mollitia unde, quod sed fugiat sapiente doloribus a repellat. Ipsum doloremque, reprehenderit quisquam fugit voluptatum quae, deserunt cumque asperiores enim nemo ullam, doloribus laudantium. Aperiam ut asperiores eum ullam distinctio saepe molestiae perspiciatis, eveniet odio deleniti corporis, enim, ipsam nostrum impedit provident voluptate fugiat? Minima eligendi recusandae unde tempore magnam, aliquid quas officia itaque est cupiditate quos harum dignissimos soluta. Fuga inventore nobis ea incidunt qui ut ullam delectus et, placeat blanditiis, fugiat accusantium. Impedit nisi delectus, architecto omnis velit natus, praesentium quidem quaerat soluta explicabo atque.</p>
        <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eos, iusto neque dolore officiis mollitia unde, quod sed fugiat sapiente doloribus a repellat. Ipsum doloremque, reprehenderit quisquam fugit voluptatum quae, deserunt cumque asperiores enim nemo ullam, doloribus laudantium. Aperiam ut asperiores eum ullam distinctio saepe molestiae perspiciatis, eveniet odio deleniti corporis, enim, ipsam nostrum impedit provident voluptate fugiat? Minima eligendi recusandae unde tempore magnam, aliquid quas officia itaque est cupiditate quos harum dignissimos soluta. Fuga inventore nobis ea incidunt qui ut ullam delectus et, placeat blanditiis, fugiat accusantium. Impedit nisi delectus, architecto omnis velit natus, praesentium quidem quaerat soluta explicabo atque.</p>
    </div>
  )
}

export default Policy