import home from '../../assets/home/home.png'
import connectivity from '../../assets/home/connectivity.png'
import building from '../../assets/home/building.png'
import techforward from '../../assets/home/techforward.png'
import beyondwork from '../../assets/home/beyondwork.png'
import brookfield from '../../assets/home/brookfield.png'
import inspirationalspaces from '../../assets/home/inspirationalspaces.png'
import sustainability from '../../assets/home/sustainability.png'
import testimonals from '../../assets/home/testimonals.png'
export default { home, connectivity, building, techforward, beyondwork, brookfield, inspirationalspaces, sustainability, testimonals };