import React from 'react'
import './Terms.css';
const Terms = () => {
    return (
        <div className="termsandconditions_content">
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Cum laboriosam consectetur possimus sapiente reiciendis delectus sed ea, earum mollitia culpa distinctio minima quae eaque eius ducimus harum eveniet dolores quos corrupti provident expedita perferendis voluptas nam! Saepe distinctio eos incidunt quas nihil nulla. Nobis molestiae atque sapiente assumenda laudantium debitis vero doloremque quas aspernatur reiciendis ut obcaecati placeat cumque ad saepe totam, a laborum quidem numquam quae! Eligendi expedita minus nam libero aliquid magni eum consequuntur magnam maxime beatae. Magni, beatae. Ipsam tempora quas aperiam repellat recusandae excepturi, assumenda distinctio quasi nesciunt velit quis saepe quae. Repellat quisquam dolore cupiditate.</p>
            <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Accusantium nobis illo, architecto eius officiis quisquam beatae, a consequuntur explicabo fuga cum cumque fugit aperiam enim perspiciatis qui dicta eaque minima dolore tempora eos! Aperiam ab, quasi nesciunt eum, inventore voluptatibus ipsam magni fugiat, repudiandae velit incidunt dignissimos tenetur temporibus dicta. Assumenda doloribus perferendis velit qui quidem dolorum delectus repellendus laudantium suscipit saepe, dolores eveniet, recusandae voluptate aut explicabo. Officiis suscipit laboriosam hic vitae veritatis, provident rerum, dolorum dolore facere eius quia repellat excepturi labore neque sequi minus aliquid enim dignissimos molestiae, quidem itaque sapiente id ex tempore? Vel, molestias adipisci?</p>
            <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Accusantium nobis illo, architecto eius officiis quisquam beatae, a consequuntur explicabo fuga cum cumque fugit aperiam enim perspiciatis qui dicta eaque minima dolore tempora eos! Aperiam ab, quasi nesciunt eum, inventore voluptatibus ipsam magni fugiat, repudiandae velit incidunt dignissimos tenetur temporibus dicta. Assumenda doloribus perferendis velit qui quidem dolorum delectus repellendus laudantium suscipit saepe, dolores eveniet, recusandae voluptate aut explicabo. Officiis suscipit laboriosam hic vitae veritatis, provident rerum, dolorum dolore facere eius quia repellat excepturi labore neque sequi minus aliquid enim dignissimos molestiae, quidem itaque sapiente id ex tempore? Vel, molestias adipisci?</p>
            <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Accusantium nobis illo, architecto eius officiis quisquam beatae, a consequuntur explicabo fuga cum cumque fugit aperiam enim perspiciatis qui dicta eaque minima dolore tempora eos! Aperiam ab, quasi nesciunt eum, inventore voluptatibus ipsam magni fugiat, repudiandae velit incidunt dignissimos tenetur temporibus dicta. Assumenda doloribus perferendis velit qui quidem dolorum delectus repellendus laudantium suscipit saepe, dolores eveniet, recusandae voluptate aut explicabo. Officiis suscipit laboriosam hic vitae veritatis, provident rerum, dolorum dolore facere eius quia repellat excepturi labore neque sequi minus aliquid enim dignissimos molestiae, quidem itaque sapiente id ex tempore? Vel, molestias adipisci?</p>
            <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Accusantium nobis illo, architecto eius officiis quisquam beatae, a consequuntur explicabo fuga cum cumque fugit aperiam enim perspiciatis qui dicta eaque minima dolore tempora eos! Aperiam ab, quasi nesciunt eum, inventore voluptatibus ipsam magni fugiat, repudiandae velit incidunt dignissimos tenetur temporibus dicta. Assumenda doloribus perferendis velit qui quidem dolorum delectus repellendus laudantium suscipit saepe, dolores eveniet, recusandae voluptate aut explicabo. Officiis suscipit laboriosam hic vitae veritatis, provident rerum, dolorum dolore facere eius quia repellat excepturi labore neque sequi minus aliquid enim dignissimos molestiae, quidem itaque sapiente id ex tempore? Vel, molestias adipisci?</p>
            <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Accusantium nobis illo, architecto eius officiis quisquam beatae, a consequuntur explicabo fuga cum cumque fugit aperiam enim perspiciatis qui dicta eaque minima dolore tempora eos! Aperiam ab, quasi nesciunt eum, inventore voluptatibus ipsam magni fugiat, repudiandae velit incidunt dignissimos tenetur temporibus dicta. Assumenda doloribus perferendis velit qui quidem dolorum delectus repellendus laudantium suscipit saepe, dolores eveniet, recusandae voluptate aut explicabo. Officiis suscipit laboriosam hic vitae veritatis, provident rerum, dolorum dolore facere eius quia repellat excepturi labore neque sequi minus aliquid enim dignissimos molestiae, quidem itaque sapiente id ex tempore? Vel, molestias adipisci?</p>
            <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Accusantium nobis illo, architecto eius officiis quisquam beatae, a consequuntur explicabo fuga cum cumque fugit aperiam enim perspiciatis qui dicta eaque minima dolore tempora eos! Aperiam ab, quasi nesciunt eum, inventore voluptatibus ipsam magni fugiat, repudiandae velit incidunt dignissimos tenetur temporibus dicta. Assumenda doloribus perferendis velit qui quidem dolorum delectus repellendus laudantium suscipit saepe, dolores eveniet, recusandae voluptate aut explicabo. Officiis suscipit laboriosam hic vitae veritatis, provident rerum, dolorum dolore facere eius quia repellat excepturi labore neque sequi minus aliquid enim dignissimos molestiae, quidem itaque sapiente id ex tempore? Vel, molestias adipisci?</p>
        </div>
    )
}

export default Terms